import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import { TRPCReactProvider } from '@/trpc/client';
import { Toaster } from '@/components/ui/sonner';
import { cn } from '@/lib/utils';
import './globals.css';

const dmSans = DM_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn('bg-white text-slate-900 antialiased custom-selection', dmSans.className)}
      >
        <TRPCReactProvider>
          {children}
          <Toaster
            toastOptions={{
              className: 'bg-white text-black border border-neutral-200 shadow-md',
              descriptionClassName: '!text-neutral-700',
            }}
          />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
