name: Check Code Formatting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.5

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile # Prevent unexpected updates
        env:
          CI: true

      - name: Check formatting with Prettier
        run: bun run format:check

      - name: Lint Code
        run: bun run lint

      - name: Type Check
        run: bun run tsc --noEmit --skipLibCheck
